/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteRouteImport } from './routes/trainer/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerHomeRouteImport } from './routes/trainer/home'
import { Route as TrainerExercisesRouteImport } from './routes/trainer/exercises'
import { Route as TrainerAnalyticsRouteImport } from './routes/trainer/analytics'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRequestResetPasswordRouteImport } from './routes/_auth/request-reset-password'
import { Route as TrainerClientsIndexRouteImport } from './routes/trainer/clients/index'
import { Route as TrainerWorkoutsWorkoutIdRouteImport } from './routes/trainer/workouts/$workoutId'
import { Route as TrainerRoutinesRoutinesLayoutRouteImport } from './routes/trainer/routines/_routinesLayout'
import { Route as TrainerRoutinesRoutineIdRouteImport } from './routes/trainer/routines/$routineId'
import { Route as TrainerAnamnesisAnamnesisLayoutRouteImport } from './routes/trainer/anamnesis/_anamnesisLayout'
import { Route as TrainerAnamnesisAnamnesisIdRouteImport } from './routes/trainer/anamnesis/$anamnesisId'
import { Route as TrainerClientsClientIdRouteRouteImport } from './routes/trainer/clients/$clientId/route'
import { Route as TrainerRoutinesRoutinesLayoutIndexRouteImport } from './routes/trainer/routines/_routinesLayout.index'
import { Route as TrainerAnamnesisAnamnesisLayoutIndexRouteImport } from './routes/trainer/anamnesis/_anamnesisLayout.index'
import { Route as TrainerRoutinesRoutinesLayoutHomugProgramsRouteImport } from './routes/trainer/routines/_routinesLayout.homug-programs'
import { Route as TrainerClientsClientIdWorkoutSessionRouteImport } from './routes/trainer/clients/$clientId/workout-session'
import { Route as TrainerClientsClientIdWeightEvolutionRouteImport } from './routes/trainer/clients/$clientId/weight-evolution'
import { Route as TrainerClientsClientIdProgramHistoryRouteImport } from './routes/trainer/clients/$clientId/program-history'
import { Route as TrainerClientsClientIdOverviewRouteImport } from './routes/trainer/clients/$clientId/overview'
import { Route as TrainerClientsClientIdMeasurementsRouteImport } from './routes/trainer/clients/$clientId/measurements'
import { Route as TrainerClientsClientIdAnamnesisRouteImport } from './routes/trainer/clients/$clientId/anamnesis'
import { Route as TrainerAnamnesisAnamnesisLayoutTemplatesRouteImport } from './routes/trainer/anamnesis/_anamnesisLayout.templates'

const TrainerRoutinesRouteImport = createFileRoute('/trainer/routines')()
const TrainerAnamnesisRouteImport = createFileRoute('/trainer/anamnesis')()

const TrainerRouteRoute = TrainerRouteRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoutinesRoute = TrainerRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerAnamnesisRoute = TrainerAnamnesisRouteImport.update({
  id: '/anamnesis',
  path: '/anamnesis',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerHomeRoute = TrainerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerExercisesRoute = TrainerExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerAnalyticsRoute = TrainerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRequestResetPasswordRoute =
  AuthRequestResetPasswordRouteImport.update({
    id: '/request-reset-password',
    path: '/request-reset-password',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const TrainerClientsIndexRoute = TrainerClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerWorkoutsWorkoutIdRoute =
  TrainerWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerRoutinesRoutinesLayoutRoute =
  TrainerRoutinesRoutinesLayoutRouteImport.update({
    id: '/_routinesLayout',
    getParentRoute: () => TrainerRoutinesRoute,
  } as any)
const TrainerRoutinesRoutineIdRoute =
  TrainerRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerAnamnesisAnamnesisLayoutRoute =
  TrainerAnamnesisAnamnesisLayoutRouteImport.update({
    id: '/_anamnesisLayout',
    getParentRoute: () => TrainerAnamnesisRoute,
  } as any)
const TrainerAnamnesisAnamnesisIdRoute =
  TrainerAnamnesisAnamnesisIdRouteImport.update({
    id: '/anamnesis/$anamnesisId',
    path: '/anamnesis/$anamnesisId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerClientsClientIdRouteRoute =
  TrainerClientsClientIdRouteRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerRoutinesRoutinesLayoutIndexRoute =
  TrainerRoutinesRoutinesLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TrainerRoutinesRoutinesLayoutRoute,
  } as any)
const TrainerAnamnesisAnamnesisLayoutIndexRoute =
  TrainerAnamnesisAnamnesisLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TrainerAnamnesisAnamnesisLayoutRoute,
  } as any)
const TrainerRoutinesRoutinesLayoutHomugProgramsRoute =
  TrainerRoutinesRoutinesLayoutHomugProgramsRouteImport.update({
    id: '/homug-programs',
    path: '/homug-programs',
    getParentRoute: () => TrainerRoutinesRoutinesLayoutRoute,
  } as any)
const TrainerClientsClientIdWorkoutSessionRoute =
  TrainerClientsClientIdWorkoutSessionRouteImport.update({
    id: '/workout-session',
    path: '/workout-session',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdWeightEvolutionRoute =
  TrainerClientsClientIdWeightEvolutionRouteImport.update({
    id: '/weight-evolution',
    path: '/weight-evolution',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdProgramHistoryRoute =
  TrainerClientsClientIdProgramHistoryRouteImport.update({
    id: '/program-history',
    path: '/program-history',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdOverviewRoute =
  TrainerClientsClientIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdMeasurementsRoute =
  TrainerClientsClientIdMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdAnamnesisRoute =
  TrainerClientsClientIdAnamnesisRouteImport.update({
    id: '/anamnesis',
    path: '/anamnesis',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerAnamnesisAnamnesisLayoutTemplatesRoute =
  TrainerAnamnesisAnamnesisLayoutTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => TrainerAnamnesisAnamnesisLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/home': typeof TrainerHomeRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRouteRouteWithChildren
  '/trainer/anamnesis/$anamnesisId': typeof TrainerAnamnesisAnamnesisIdRoute
  '/trainer/anamnesis': typeof TrainerAnamnesisAnamnesisLayoutRouteWithChildren
  '/trainer/routines/$routineId': typeof TrainerRoutinesRoutineIdRoute
  '/trainer/routines': typeof TrainerRoutinesRoutinesLayoutRouteWithChildren
  '/trainer/workouts/$workoutId': typeof TrainerWorkoutsWorkoutIdRoute
  '/trainer/clients': typeof TrainerClientsIndexRoute
  '/trainer/anamnesis/templates': typeof TrainerAnamnesisAnamnesisLayoutTemplatesRoute
  '/trainer/clients/$clientId/anamnesis': typeof TrainerClientsClientIdAnamnesisRoute
  '/trainer/clients/$clientId/measurements': typeof TrainerClientsClientIdMeasurementsRoute
  '/trainer/clients/$clientId/overview': typeof TrainerClientsClientIdOverviewRoute
  '/trainer/clients/$clientId/program-history': typeof TrainerClientsClientIdProgramHistoryRoute
  '/trainer/clients/$clientId/weight-evolution': typeof TrainerClientsClientIdWeightEvolutionRoute
  '/trainer/clients/$clientId/workout-session': typeof TrainerClientsClientIdWorkoutSessionRoute
  '/trainer/routines/homug-programs': typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  '/trainer/anamnesis/': typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
  '/trainer/routines/': typeof TrainerRoutinesRoutinesLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/home': typeof TrainerHomeRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRouteRouteWithChildren
  '/trainer/anamnesis/$anamnesisId': typeof TrainerAnamnesisAnamnesisIdRoute
  '/trainer/anamnesis': typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
  '/trainer/routines/$routineId': typeof TrainerRoutinesRoutineIdRoute
  '/trainer/routines': typeof TrainerRoutinesRoutinesLayoutIndexRoute
  '/trainer/workouts/$workoutId': typeof TrainerWorkoutsWorkoutIdRoute
  '/trainer/clients': typeof TrainerClientsIndexRoute
  '/trainer/anamnesis/templates': typeof TrainerAnamnesisAnamnesisLayoutTemplatesRoute
  '/trainer/clients/$clientId/anamnesis': typeof TrainerClientsClientIdAnamnesisRoute
  '/trainer/clients/$clientId/measurements': typeof TrainerClientsClientIdMeasurementsRoute
  '/trainer/clients/$clientId/overview': typeof TrainerClientsClientIdOverviewRoute
  '/trainer/clients/$clientId/program-history': typeof TrainerClientsClientIdProgramHistoryRoute
  '/trainer/clients/$clientId/weight-evolution': typeof TrainerClientsClientIdWeightEvolutionRoute
  '/trainer/clients/$clientId/workout-session': typeof TrainerClientsClientIdWorkoutSessionRoute
  '/trainer/routines/homug-programs': typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/_auth/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/home': typeof TrainerHomeRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRouteRouteWithChildren
  '/trainer/anamnesis/$anamnesisId': typeof TrainerAnamnesisAnamnesisIdRoute
  '/trainer/anamnesis': typeof TrainerAnamnesisRouteWithChildren
  '/trainer/anamnesis/_anamnesisLayout': typeof TrainerAnamnesisAnamnesisLayoutRouteWithChildren
  '/trainer/routines/$routineId': typeof TrainerRoutinesRoutineIdRoute
  '/trainer/routines': typeof TrainerRoutinesRouteWithChildren
  '/trainer/routines/_routinesLayout': typeof TrainerRoutinesRoutinesLayoutRouteWithChildren
  '/trainer/workouts/$workoutId': typeof TrainerWorkoutsWorkoutIdRoute
  '/trainer/clients/': typeof TrainerClientsIndexRoute
  '/trainer/anamnesis/_anamnesisLayout/templates': typeof TrainerAnamnesisAnamnesisLayoutTemplatesRoute
  '/trainer/clients/$clientId/anamnesis': typeof TrainerClientsClientIdAnamnesisRoute
  '/trainer/clients/$clientId/measurements': typeof TrainerClientsClientIdMeasurementsRoute
  '/trainer/clients/$clientId/overview': typeof TrainerClientsClientIdOverviewRoute
  '/trainer/clients/$clientId/program-history': typeof TrainerClientsClientIdProgramHistoryRoute
  '/trainer/clients/$clientId/weight-evolution': typeof TrainerClientsClientIdWeightEvolutionRoute
  '/trainer/clients/$clientId/workout-session': typeof TrainerClientsClientIdWorkoutSessionRoute
  '/trainer/routines/_routinesLayout/homug-programs': typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  '/trainer/anamnesis/_anamnesisLayout/': typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
  '/trainer/routines/_routinesLayout/': typeof TrainerRoutinesRoutinesLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trainer'
    | '/request-reset-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/trainer/analytics'
    | '/trainer/exercises'
    | '/trainer/home'
    | '/trainer/clients/$clientId'
    | '/trainer/anamnesis/$anamnesisId'
    | '/trainer/anamnesis'
    | '/trainer/routines/$routineId'
    | '/trainer/routines'
    | '/trainer/workouts/$workoutId'
    | '/trainer/clients'
    | '/trainer/anamnesis/templates'
    | '/trainer/clients/$clientId/anamnesis'
    | '/trainer/clients/$clientId/measurements'
    | '/trainer/clients/$clientId/overview'
    | '/trainer/clients/$clientId/program-history'
    | '/trainer/clients/$clientId/weight-evolution'
    | '/trainer/clients/$clientId/workout-session'
    | '/trainer/routines/homug-programs'
    | '/trainer/anamnesis/'
    | '/trainer/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trainer'
    | '/request-reset-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/trainer/analytics'
    | '/trainer/exercises'
    | '/trainer/home'
    | '/trainer/clients/$clientId'
    | '/trainer/anamnesis/$anamnesisId'
    | '/trainer/anamnesis'
    | '/trainer/routines/$routineId'
    | '/trainer/routines'
    | '/trainer/workouts/$workoutId'
    | '/trainer/clients'
    | '/trainer/anamnesis/templates'
    | '/trainer/clients/$clientId/anamnesis'
    | '/trainer/clients/$clientId/measurements'
    | '/trainer/clients/$clientId/overview'
    | '/trainer/clients/$clientId/program-history'
    | '/trainer/clients/$clientId/weight-evolution'
    | '/trainer/clients/$clientId/workout-session'
    | '/trainer/routines/homug-programs'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/trainer'
    | '/_auth/request-reset-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/trainer/analytics'
    | '/trainer/exercises'
    | '/trainer/home'
    | '/trainer/clients/$clientId'
    | '/trainer/anamnesis/$anamnesisId'
    | '/trainer/anamnesis'
    | '/trainer/anamnesis/_anamnesisLayout'
    | '/trainer/routines/$routineId'
    | '/trainer/routines'
    | '/trainer/routines/_routinesLayout'
    | '/trainer/workouts/$workoutId'
    | '/trainer/clients/'
    | '/trainer/anamnesis/_anamnesisLayout/templates'
    | '/trainer/clients/$clientId/anamnesis'
    | '/trainer/clients/$clientId/measurements'
    | '/trainer/clients/$clientId/overview'
    | '/trainer/clients/$clientId/program-history'
    | '/trainer/clients/$clientId/weight-evolution'
    | '/trainer/clients/$clientId/workout-session'
    | '/trainer/routines/_routinesLayout/homug-programs'
    | '/trainer/anamnesis/_anamnesisLayout/'
    | '/trainer/routines/_routinesLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  TrainerRouteRoute: typeof TrainerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/routines': {
      id: '/trainer/routines'
      path: '/routines'
      fullPath: '/trainer/routines'
      preLoaderRoute: typeof TrainerRoutinesRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/anamnesis': {
      id: '/trainer/anamnesis'
      path: '/anamnesis'
      fullPath: '/trainer/anamnesis'
      preLoaderRoute: typeof TrainerAnamnesisRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/home': {
      id: '/trainer/home'
      path: '/home'
      fullPath: '/trainer/home'
      preLoaderRoute: typeof TrainerHomeRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/exercises': {
      id: '/trainer/exercises'
      path: '/exercises'
      fullPath: '/trainer/exercises'
      preLoaderRoute: typeof TrainerExercisesRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/analytics': {
      id: '/trainer/analytics'
      path: '/analytics'
      fullPath: '/trainer/analytics'
      preLoaderRoute: typeof TrainerAnalyticsRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/request-reset-password': {
      id: '/_auth/request-reset-password'
      path: '/request-reset-password'
      fullPath: '/request-reset-password'
      preLoaderRoute: typeof AuthRequestResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/trainer/clients/': {
      id: '/trainer/clients/'
      path: '/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsIndexRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/workouts/$workoutId': {
      id: '/trainer/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/trainer/workouts/$workoutId'
      preLoaderRoute: typeof TrainerWorkoutsWorkoutIdRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/routines/_routinesLayout': {
      id: '/trainer/routines/_routinesLayout'
      path: '/routines'
      fullPath: '/trainer/routines'
      preLoaderRoute: typeof TrainerRoutinesRoutinesLayoutRouteImport
      parentRoute: typeof TrainerRoutinesRoute
    }
    '/trainer/routines/$routineId': {
      id: '/trainer/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/trainer/routines/$routineId'
      preLoaderRoute: typeof TrainerRoutinesRoutineIdRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/anamnesis/_anamnesisLayout': {
      id: '/trainer/anamnesis/_anamnesisLayout'
      path: '/anamnesis'
      fullPath: '/trainer/anamnesis'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisLayoutRouteImport
      parentRoute: typeof TrainerAnamnesisRoute
    }
    '/trainer/anamnesis/$anamnesisId': {
      id: '/trainer/anamnesis/$anamnesisId'
      path: '/anamnesis/$anamnesisId'
      fullPath: '/trainer/anamnesis/$anamnesisId'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisIdRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/clients/$clientId': {
      id: '/trainer/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/trainer/clients/$clientId'
      preLoaderRoute: typeof TrainerClientsClientIdRouteRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/routines/_routinesLayout/': {
      id: '/trainer/routines/_routinesLayout/'
      path: '/'
      fullPath: '/trainer/routines/'
      preLoaderRoute: typeof TrainerRoutinesRoutinesLayoutIndexRouteImport
      parentRoute: typeof TrainerRoutinesRoutinesLayoutRoute
    }
    '/trainer/anamnesis/_anamnesisLayout/': {
      id: '/trainer/anamnesis/_anamnesisLayout/'
      path: '/'
      fullPath: '/trainer/anamnesis/'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisLayoutIndexRouteImport
      parentRoute: typeof TrainerAnamnesisAnamnesisLayoutRoute
    }
    '/trainer/routines/_routinesLayout/homug-programs': {
      id: '/trainer/routines/_routinesLayout/homug-programs'
      path: '/homug-programs'
      fullPath: '/trainer/routines/homug-programs'
      preLoaderRoute: typeof TrainerRoutinesRoutinesLayoutHomugProgramsRouteImport
      parentRoute: typeof TrainerRoutinesRoutinesLayoutRoute
    }
    '/trainer/clients/$clientId/workout-session': {
      id: '/trainer/clients/$clientId/workout-session'
      path: '/workout-session'
      fullPath: '/trainer/clients/$clientId/workout-session'
      preLoaderRoute: typeof TrainerClientsClientIdWorkoutSessionRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/weight-evolution': {
      id: '/trainer/clients/$clientId/weight-evolution'
      path: '/weight-evolution'
      fullPath: '/trainer/clients/$clientId/weight-evolution'
      preLoaderRoute: typeof TrainerClientsClientIdWeightEvolutionRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/program-history': {
      id: '/trainer/clients/$clientId/program-history'
      path: '/program-history'
      fullPath: '/trainer/clients/$clientId/program-history'
      preLoaderRoute: typeof TrainerClientsClientIdProgramHistoryRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/overview': {
      id: '/trainer/clients/$clientId/overview'
      path: '/overview'
      fullPath: '/trainer/clients/$clientId/overview'
      preLoaderRoute: typeof TrainerClientsClientIdOverviewRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/measurements': {
      id: '/trainer/clients/$clientId/measurements'
      path: '/measurements'
      fullPath: '/trainer/clients/$clientId/measurements'
      preLoaderRoute: typeof TrainerClientsClientIdMeasurementsRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/anamnesis': {
      id: '/trainer/clients/$clientId/anamnesis'
      path: '/anamnesis'
      fullPath: '/trainer/clients/$clientId/anamnesis'
      preLoaderRoute: typeof TrainerClientsClientIdAnamnesisRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/anamnesis/_anamnesisLayout/templates': {
      id: '/trainer/anamnesis/_anamnesisLayout/templates'
      path: '/templates'
      fullPath: '/trainer/anamnesis/templates'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisLayoutTemplatesRouteImport
      parentRoute: typeof TrainerAnamnesisAnamnesisLayoutRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRequestResetPasswordRoute: typeof AuthRequestResetPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRequestResetPasswordRoute: AuthRequestResetPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface TrainerClientsClientIdRouteRouteChildren {
  TrainerClientsClientIdAnamnesisRoute: typeof TrainerClientsClientIdAnamnesisRoute
  TrainerClientsClientIdMeasurementsRoute: typeof TrainerClientsClientIdMeasurementsRoute
  TrainerClientsClientIdOverviewRoute: typeof TrainerClientsClientIdOverviewRoute
  TrainerClientsClientIdProgramHistoryRoute: typeof TrainerClientsClientIdProgramHistoryRoute
  TrainerClientsClientIdWeightEvolutionRoute: typeof TrainerClientsClientIdWeightEvolutionRoute
  TrainerClientsClientIdWorkoutSessionRoute: typeof TrainerClientsClientIdWorkoutSessionRoute
}

const TrainerClientsClientIdRouteRouteChildren: TrainerClientsClientIdRouteRouteChildren =
  {
    TrainerClientsClientIdAnamnesisRoute: TrainerClientsClientIdAnamnesisRoute,
    TrainerClientsClientIdMeasurementsRoute:
      TrainerClientsClientIdMeasurementsRoute,
    TrainerClientsClientIdOverviewRoute: TrainerClientsClientIdOverviewRoute,
    TrainerClientsClientIdProgramHistoryRoute:
      TrainerClientsClientIdProgramHistoryRoute,
    TrainerClientsClientIdWeightEvolutionRoute:
      TrainerClientsClientIdWeightEvolutionRoute,
    TrainerClientsClientIdWorkoutSessionRoute:
      TrainerClientsClientIdWorkoutSessionRoute,
  }

const TrainerClientsClientIdRouteRouteWithChildren =
  TrainerClientsClientIdRouteRoute._addFileChildren(
    TrainerClientsClientIdRouteRouteChildren,
  )

interface TrainerAnamnesisAnamnesisLayoutRouteChildren {
  TrainerAnamnesisAnamnesisLayoutTemplatesRoute: typeof TrainerAnamnesisAnamnesisLayoutTemplatesRoute
  TrainerAnamnesisAnamnesisLayoutIndexRoute: typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
}

const TrainerAnamnesisAnamnesisLayoutRouteChildren: TrainerAnamnesisAnamnesisLayoutRouteChildren =
  {
    TrainerAnamnesisAnamnesisLayoutTemplatesRoute:
      TrainerAnamnesisAnamnesisLayoutTemplatesRoute,
    TrainerAnamnesisAnamnesisLayoutIndexRoute:
      TrainerAnamnesisAnamnesisLayoutIndexRoute,
  }

const TrainerAnamnesisAnamnesisLayoutRouteWithChildren =
  TrainerAnamnesisAnamnesisLayoutRoute._addFileChildren(
    TrainerAnamnesisAnamnesisLayoutRouteChildren,
  )

interface TrainerAnamnesisRouteChildren {
  TrainerAnamnesisAnamnesisLayoutRoute: typeof TrainerAnamnesisAnamnesisLayoutRouteWithChildren
}

const TrainerAnamnesisRouteChildren: TrainerAnamnesisRouteChildren = {
  TrainerAnamnesisAnamnesisLayoutRoute:
    TrainerAnamnesisAnamnesisLayoutRouteWithChildren,
}

const TrainerAnamnesisRouteWithChildren =
  TrainerAnamnesisRoute._addFileChildren(TrainerAnamnesisRouteChildren)

interface TrainerRoutinesRoutinesLayoutRouteChildren {
  TrainerRoutinesRoutinesLayoutHomugProgramsRoute: typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  TrainerRoutinesRoutinesLayoutIndexRoute: typeof TrainerRoutinesRoutinesLayoutIndexRoute
}

const TrainerRoutinesRoutinesLayoutRouteChildren: TrainerRoutinesRoutinesLayoutRouteChildren =
  {
    TrainerRoutinesRoutinesLayoutHomugProgramsRoute:
      TrainerRoutinesRoutinesLayoutHomugProgramsRoute,
    TrainerRoutinesRoutinesLayoutIndexRoute:
      TrainerRoutinesRoutinesLayoutIndexRoute,
  }

const TrainerRoutinesRoutinesLayoutRouteWithChildren =
  TrainerRoutinesRoutinesLayoutRoute._addFileChildren(
    TrainerRoutinesRoutinesLayoutRouteChildren,
  )

interface TrainerRoutinesRouteChildren {
  TrainerRoutinesRoutinesLayoutRoute: typeof TrainerRoutinesRoutinesLayoutRouteWithChildren
}

const TrainerRoutinesRouteChildren: TrainerRoutinesRouteChildren = {
  TrainerRoutinesRoutinesLayoutRoute:
    TrainerRoutinesRoutinesLayoutRouteWithChildren,
}

const TrainerRoutinesRouteWithChildren = TrainerRoutinesRoute._addFileChildren(
  TrainerRoutinesRouteChildren,
)

interface TrainerRouteRouteChildren {
  TrainerAnalyticsRoute: typeof TrainerAnalyticsRoute
  TrainerExercisesRoute: typeof TrainerExercisesRoute
  TrainerHomeRoute: typeof TrainerHomeRoute
  TrainerClientsClientIdRouteRoute: typeof TrainerClientsClientIdRouteRouteWithChildren
  TrainerAnamnesisAnamnesisIdRoute: typeof TrainerAnamnesisAnamnesisIdRoute
  TrainerAnamnesisRoute: typeof TrainerAnamnesisRouteWithChildren
  TrainerRoutinesRoutineIdRoute: typeof TrainerRoutinesRoutineIdRoute
  TrainerRoutinesRoute: typeof TrainerRoutinesRouteWithChildren
  TrainerWorkoutsWorkoutIdRoute: typeof TrainerWorkoutsWorkoutIdRoute
  TrainerClientsIndexRoute: typeof TrainerClientsIndexRoute
}

const TrainerRouteRouteChildren: TrainerRouteRouteChildren = {
  TrainerAnalyticsRoute: TrainerAnalyticsRoute,
  TrainerExercisesRoute: TrainerExercisesRoute,
  TrainerHomeRoute: TrainerHomeRoute,
  TrainerClientsClientIdRouteRoute:
    TrainerClientsClientIdRouteRouteWithChildren,
  TrainerAnamnesisAnamnesisIdRoute: TrainerAnamnesisAnamnesisIdRoute,
  TrainerAnamnesisRoute: TrainerAnamnesisRouteWithChildren,
  TrainerRoutinesRoutineIdRoute: TrainerRoutinesRoutineIdRoute,
  TrainerRoutinesRoute: TrainerRoutinesRouteWithChildren,
  TrainerWorkoutsWorkoutIdRoute: TrainerWorkoutsWorkoutIdRoute,
  TrainerClientsIndexRoute: TrainerClientsIndexRoute,
}

const TrainerRouteRouteWithChildren = TrainerRouteRoute._addFileChildren(
  TrainerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  TrainerRouteRoute: TrainerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
