/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as TrainerRouteRouteImport } from './routes/trainer/route'
import { Route as ClientRouteRouteImport } from './routes/client/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer/index'
import { Route as TrainerHomeRouteImport } from './routes/trainer/home'
import { Route as TrainerExercisesRouteImport } from './routes/trainer/exercises'
import { Route as TrainerAnalyticsRouteImport } from './routes/trainer/analytics'
import { Route as ClientSetPasswordRouteImport } from './routes/client/set-password'
import { Route as ClientActivitiesRouteImport } from './routes/client/activities'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ClienttabsRouteRouteImport } from './routes/client/(tabs)/route'
import { Route as TrainerClientsIndexRouteImport } from './routes/trainer/clients/index'
import { Route as ClientAnamnesesIndexRouteImport } from './routes/client/anamneses/index'
import { Route as TrainerWorkoutsWorkoutIdRouteImport } from './routes/trainer/workouts/$workoutId'
import { Route as TrainerRoutinesRoutinesLayoutRouteImport } from './routes/trainer/routines/_routinesLayout'
import { Route as TrainerRoutinesRoutineIdRouteImport } from './routes/trainer/routines/$routineId'
import { Route as TrainerAnamnesisAnamnesisLayoutRouteImport } from './routes/trainer/anamnesis/_anamnesisLayout'
import { Route as TrainerAnamnesisAnamnesisIdRouteImport } from './routes/trainer/anamnesis/$anamnesisId'
import { Route as ClientSessionsSelectExerciseRouteImport } from './routes/client/sessions/select-exercise'
import { Route as ClientSessionsActiveRouteImport } from './routes/client/sessions/active'
import { Route as ClientProfileEditRouteImport } from './routes/client/profile/edit'
import { Route as ClientExercisesExerciseIdRouteImport } from './routes/client/exercises/$exerciseId'
import { Route as ClienttabsWorkoutsRouteImport } from './routes/client/(tabs)/workouts'
import { Route as ClienttabsProfileRouteImport } from './routes/client/(tabs)/profile'
import { Route as ClienttabsHomeRouteImport } from './routes/client/(tabs)/home'
import { Route as ClienttabsHistoryRouteImport } from './routes/client/(tabs)/history'
import { Route as TrainerClientsClientIdRouteRouteImport } from './routes/trainer/clients/$clientId/route'
import { Route as TrainerAccountsectionsRouteRouteImport } from './routes/trainer/account/(sections)/route'
import { Route as TrainerRoutinesRoutinesLayoutIndexRouteImport } from './routes/trainer/routines/_routinesLayout.index'
import { Route as TrainerAnamnesisAnamnesisLayoutIndexRouteImport } from './routes/trainer/anamnesis/_anamnesisLayout.index'
import { Route as TrainerAccountsectionsIndexRouteImport } from './routes/trainer/account/(sections)/index'
import { Route as ClientAnamnesesClientAnamnesisIdIndexRouteImport } from './routes/client/anamneses/$clientAnamnesisId/index'
import { Route as TrainerRoutinesRoutinesLayoutHomugProgramsRouteImport } from './routes/trainer/routines/_routinesLayout.homug-programs'
import { Route as TrainerClientsClientIdWorkoutSessionRouteImport } from './routes/trainer/clients/$clientId/workout-session'
import { Route as TrainerClientsClientIdWeightEvolutionRouteImport } from './routes/trainer/clients/$clientId/weight-evolution'
import { Route as TrainerClientsClientIdProgramHistoryRouteImport } from './routes/trainer/clients/$clientId/program-history'
import { Route as TrainerClientsClientIdOverviewRouteImport } from './routes/trainer/clients/$clientId/overview'
import { Route as TrainerClientsClientIdMeasurementsRouteImport } from './routes/trainer/clients/$clientId/measurements'
import { Route as TrainerClientsClientIdAnamnesisRouteImport } from './routes/trainer/clients/$clientId/anamnesis'
import { Route as TrainerAccountsectionsTemaRouteImport } from './routes/trainer/account/(sections)/tema'
import { Route as TrainerAccountsectionsPreferenceRouteImport } from './routes/trainer/account/(sections)/preference'
import { Route as TrainerAccountsectionsPlanoRouteImport } from './routes/trainer/account/(sections)/plano'
import { Route as TrainerAccountsectionsContaRouteImport } from './routes/trainer/account/(sections)/conta'
import { Route as ClientSessionsActiveSaveRouteImport } from './routes/client/sessions/active.save'
import { Route as ClientAnamnesesClientAnamnesisIdRespondRouteImport } from './routes/client/anamneses/$clientAnamnesisId/respond'

const TrainerRoutinesRouteImport = createFileRoute('/trainer/routines')()
const TrainerAnamnesisRouteImport = createFileRoute('/trainer/anamnesis')()

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRouteRoute = TrainerRouteRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRouteRoute = ClientRouteRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoutinesRoute = TrainerRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerAnamnesisRoute = TrainerAnamnesisRouteImport.update({
  id: '/anamnesis',
  path: '/anamnesis',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerHomeRoute = TrainerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerExercisesRoute = TrainerExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const TrainerAnalyticsRoute = TrainerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const ClientSetPasswordRoute = ClientSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientActivitiesRoute = ClientActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => ClientRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ClienttabsRouteRoute = ClienttabsRouteRouteImport.update({
  id: '/(tabs)',
  getParentRoute: () => ClientRouteRoute,
} as any)
const TrainerClientsIndexRoute = TrainerClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => TrainerRouteRoute,
} as any)
const ClientAnamnesesIndexRoute = ClientAnamnesesIndexRouteImport.update({
  id: '/anamneses/',
  path: '/anamneses/',
  getParentRoute: () => ClientRouteRoute,
} as any)
const TrainerWorkoutsWorkoutIdRoute =
  TrainerWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerRoutinesRoutinesLayoutRoute =
  TrainerRoutinesRoutinesLayoutRouteImport.update({
    id: '/_routinesLayout',
    getParentRoute: () => TrainerRoutinesRoute,
  } as any)
const TrainerRoutinesRoutineIdRoute =
  TrainerRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerAnamnesisAnamnesisLayoutRoute =
  TrainerAnamnesisAnamnesisLayoutRouteImport.update({
    id: '/_anamnesisLayout',
    getParentRoute: () => TrainerAnamnesisRoute,
  } as any)
const TrainerAnamnesisAnamnesisIdRoute =
  TrainerAnamnesisAnamnesisIdRouteImport.update({
    id: '/anamnesis/$anamnesisId',
    path: '/anamnesis/$anamnesisId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const ClientSessionsSelectExerciseRoute =
  ClientSessionsSelectExerciseRouteImport.update({
    id: '/sessions/select-exercise',
    path: '/sessions/select-exercise',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClientSessionsActiveRoute = ClientSessionsActiveRouteImport.update({
  id: '/sessions/active',
  path: '/sessions/active',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientProfileEditRoute = ClientProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => ClientRouteRoute,
} as any)
const ClientExercisesExerciseIdRoute =
  ClientExercisesExerciseIdRouteImport.update({
    id: '/exercises/$exerciseId',
    path: '/exercises/$exerciseId',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const ClienttabsWorkoutsRoute = ClienttabsWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => ClienttabsRouteRoute,
} as any)
const ClienttabsProfileRoute = ClienttabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClienttabsRouteRoute,
} as any)
const ClienttabsHomeRoute = ClienttabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ClienttabsRouteRoute,
} as any)
const ClienttabsHistoryRoute = ClienttabsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ClienttabsRouteRoute,
} as any)
const TrainerClientsClientIdRouteRoute =
  TrainerClientsClientIdRouteRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerAccountsectionsRouteRoute =
  TrainerAccountsectionsRouteRouteImport.update({
    id: '/account/(sections)',
    path: '/account',
    getParentRoute: () => TrainerRouteRoute,
  } as any)
const TrainerRoutinesRoutinesLayoutIndexRoute =
  TrainerRoutinesRoutinesLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TrainerRoutinesRoutinesLayoutRoute,
  } as any)
const TrainerAnamnesisAnamnesisLayoutIndexRoute =
  TrainerAnamnesisAnamnesisLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TrainerAnamnesisAnamnesisLayoutRoute,
  } as any)
const TrainerAccountsectionsIndexRoute =
  TrainerAccountsectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TrainerAccountsectionsRouteRoute,
  } as any)
const ClientAnamnesesClientAnamnesisIdIndexRoute =
  ClientAnamnesesClientAnamnesisIdIndexRouteImport.update({
    id: '/anamneses/$clientAnamnesisId/',
    path: '/anamneses/$clientAnamnesisId/',
    getParentRoute: () => ClientRouteRoute,
  } as any)
const TrainerRoutinesRoutinesLayoutHomugProgramsRoute =
  TrainerRoutinesRoutinesLayoutHomugProgramsRouteImport.update({
    id: '/homug-programs',
    path: '/homug-programs',
    getParentRoute: () => TrainerRoutinesRoutinesLayoutRoute,
  } as any)
const TrainerClientsClientIdWorkoutSessionRoute =
  TrainerClientsClientIdWorkoutSessionRouteImport.update({
    id: '/workout-session',
    path: '/workout-session',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdWeightEvolutionRoute =
  TrainerClientsClientIdWeightEvolutionRouteImport.update({
    id: '/weight-evolution',
    path: '/weight-evolution',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdProgramHistoryRoute =
  TrainerClientsClientIdProgramHistoryRouteImport.update({
    id: '/program-history',
    path: '/program-history',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdOverviewRoute =
  TrainerClientsClientIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdMeasurementsRoute =
  TrainerClientsClientIdMeasurementsRouteImport.update({
    id: '/measurements',
    path: '/measurements',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerClientsClientIdAnamnesisRoute =
  TrainerClientsClientIdAnamnesisRouteImport.update({
    id: '/anamnesis',
    path: '/anamnesis',
    getParentRoute: () => TrainerClientsClientIdRouteRoute,
  } as any)
const TrainerAccountsectionsTemaRoute =
  TrainerAccountsectionsTemaRouteImport.update({
    id: '/tema',
    path: '/tema',
    getParentRoute: () => TrainerAccountsectionsRouteRoute,
  } as any)
const TrainerAccountsectionsPreferenceRoute =
  TrainerAccountsectionsPreferenceRouteImport.update({
    id: '/preference',
    path: '/preference',
    getParentRoute: () => TrainerAccountsectionsRouteRoute,
  } as any)
const TrainerAccountsectionsPlanoRoute =
  TrainerAccountsectionsPlanoRouteImport.update({
    id: '/plano',
    path: '/plano',
    getParentRoute: () => TrainerAccountsectionsRouteRoute,
  } as any)
const TrainerAccountsectionsContaRoute =
  TrainerAccountsectionsContaRouteImport.update({
    id: '/conta',
    path: '/conta',
    getParentRoute: () => TrainerAccountsectionsRouteRoute,
  } as any)
const ClientSessionsActiveSaveRoute =
  ClientSessionsActiveSaveRouteImport.update({
    id: '/save',
    path: '/save',
    getParentRoute: () => ClientSessionsActiveRoute,
  } as any)
const ClientAnamnesesClientAnamnesisIdRespondRoute =
  ClientAnamnesesClientAnamnesisIdRespondRouteImport.update({
    id: '/anamneses/$clientAnamnesisId/respond',
    path: '/anamneses/$clientAnamnesisId/respond',
    getParentRoute: () => ClientRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClienttabsRouteRouteWithChildren
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/client/activities': typeof ClientActivitiesRoute
  '/client/set-password': typeof ClientSetPasswordRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/home': typeof TrainerHomeRoute
  '/trainer/': typeof TrainerIndexRoute
  '/trainer/account': typeof TrainerAccountsectionsRouteRouteWithChildren
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRouteRouteWithChildren
  '/client/history': typeof ClienttabsHistoryRoute
  '/client/home': typeof ClienttabsHomeRoute
  '/client/profile': typeof ClienttabsProfileRoute
  '/client/workouts': typeof ClienttabsWorkoutsRoute
  '/client/exercises/$exerciseId': typeof ClientExercisesExerciseIdRoute
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/sessions/active': typeof ClientSessionsActiveRouteWithChildren
  '/client/sessions/select-exercise': typeof ClientSessionsSelectExerciseRoute
  '/trainer/anamnesis/$anamnesisId': typeof TrainerAnamnesisAnamnesisIdRoute
  '/trainer/anamnesis': typeof TrainerAnamnesisAnamnesisLayoutRouteWithChildren
  '/trainer/routines/$routineId': typeof TrainerRoutinesRoutineIdRoute
  '/trainer/routines': typeof TrainerRoutinesRoutinesLayoutRouteWithChildren
  '/trainer/workouts/$workoutId': typeof TrainerWorkoutsWorkoutIdRoute
  '/client/anamneses': typeof ClientAnamnesesIndexRoute
  '/trainer/clients': typeof TrainerClientsIndexRoute
  '/client/anamneses/$clientAnamnesisId/respond': typeof ClientAnamnesesClientAnamnesisIdRespondRoute
  '/client/sessions/active/save': typeof ClientSessionsActiveSaveRoute
  '/trainer/account/conta': typeof TrainerAccountsectionsContaRoute
  '/trainer/account/plano': typeof TrainerAccountsectionsPlanoRoute
  '/trainer/account/preference': typeof TrainerAccountsectionsPreferenceRoute
  '/trainer/account/tema': typeof TrainerAccountsectionsTemaRoute
  '/trainer/clients/$clientId/anamnesis': typeof TrainerClientsClientIdAnamnesisRoute
  '/trainer/clients/$clientId/measurements': typeof TrainerClientsClientIdMeasurementsRoute
  '/trainer/clients/$clientId/overview': typeof TrainerClientsClientIdOverviewRoute
  '/trainer/clients/$clientId/program-history': typeof TrainerClientsClientIdProgramHistoryRoute
  '/trainer/clients/$clientId/weight-evolution': typeof TrainerClientsClientIdWeightEvolutionRoute
  '/trainer/clients/$clientId/workout-session': typeof TrainerClientsClientIdWorkoutSessionRoute
  '/trainer/routines/homug-programs': typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  '/client/anamneses/$clientAnamnesisId': typeof ClientAnamnesesClientAnamnesisIdIndexRoute
  '/trainer/account/': typeof TrainerAccountsectionsIndexRoute
  '/trainer/anamnesis/': typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
  '/trainer/routines/': typeof TrainerRoutinesRoutinesLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClienttabsRouteRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/client/activities': typeof ClientActivitiesRoute
  '/client/set-password': typeof ClientSetPasswordRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/home': typeof TrainerHomeRoute
  '/trainer': typeof TrainerIndexRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRouteRouteWithChildren
  '/client/history': typeof ClienttabsHistoryRoute
  '/client/home': typeof ClienttabsHomeRoute
  '/client/profile': typeof ClienttabsProfileRoute
  '/client/workouts': typeof ClienttabsWorkoutsRoute
  '/client/exercises/$exerciseId': typeof ClientExercisesExerciseIdRoute
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/sessions/active': typeof ClientSessionsActiveRouteWithChildren
  '/client/sessions/select-exercise': typeof ClientSessionsSelectExerciseRoute
  '/trainer/anamnesis/$anamnesisId': typeof TrainerAnamnesisAnamnesisIdRoute
  '/trainer/anamnesis': typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
  '/trainer/routines/$routineId': typeof TrainerRoutinesRoutineIdRoute
  '/trainer/routines': typeof TrainerRoutinesRoutinesLayoutIndexRoute
  '/trainer/workouts/$workoutId': typeof TrainerWorkoutsWorkoutIdRoute
  '/client/anamneses': typeof ClientAnamnesesIndexRoute
  '/trainer/clients': typeof TrainerClientsIndexRoute
  '/client/anamneses/$clientAnamnesisId/respond': typeof ClientAnamnesesClientAnamnesisIdRespondRoute
  '/client/sessions/active/save': typeof ClientSessionsActiveSaveRoute
  '/trainer/account/conta': typeof TrainerAccountsectionsContaRoute
  '/trainer/account/plano': typeof TrainerAccountsectionsPlanoRoute
  '/trainer/account/preference': typeof TrainerAccountsectionsPreferenceRoute
  '/trainer/account/tema': typeof TrainerAccountsectionsTemaRoute
  '/trainer/clients/$clientId/anamnesis': typeof TrainerClientsClientIdAnamnesisRoute
  '/trainer/clients/$clientId/measurements': typeof TrainerClientsClientIdMeasurementsRoute
  '/trainer/clients/$clientId/overview': typeof TrainerClientsClientIdOverviewRoute
  '/trainer/clients/$clientId/program-history': typeof TrainerClientsClientIdProgramHistoryRoute
  '/trainer/clients/$clientId/weight-evolution': typeof TrainerClientsClientIdWeightEvolutionRoute
  '/trainer/clients/$clientId/workout-session': typeof TrainerClientsClientIdWorkoutSessionRoute
  '/trainer/routines/homug-programs': typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  '/client/anamneses/$clientAnamnesisId': typeof ClientAnamnesesClientAnamnesisIdIndexRoute
  '/trainer/account': typeof TrainerAccountsectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/client': typeof ClientRouteRouteWithChildren
  '/trainer': typeof TrainerRouteRouteWithChildren
  '/email-verified': typeof EmailVerifiedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/client/(tabs)': typeof ClienttabsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/client/activities': typeof ClientActivitiesRoute
  '/client/set-password': typeof ClientSetPasswordRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/exercises': typeof TrainerExercisesRoute
  '/trainer/home': typeof TrainerHomeRoute
  '/trainer/': typeof TrainerIndexRoute
  '/trainer/account/(sections)': typeof TrainerAccountsectionsRouteRouteWithChildren
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRouteRouteWithChildren
  '/client/(tabs)/history': typeof ClienttabsHistoryRoute
  '/client/(tabs)/home': typeof ClienttabsHomeRoute
  '/client/(tabs)/profile': typeof ClienttabsProfileRoute
  '/client/(tabs)/workouts': typeof ClienttabsWorkoutsRoute
  '/client/exercises/$exerciseId': typeof ClientExercisesExerciseIdRoute
  '/client/profile/edit': typeof ClientProfileEditRoute
  '/client/sessions/active': typeof ClientSessionsActiveRouteWithChildren
  '/client/sessions/select-exercise': typeof ClientSessionsSelectExerciseRoute
  '/trainer/anamnesis/$anamnesisId': typeof TrainerAnamnesisAnamnesisIdRoute
  '/trainer/anamnesis': typeof TrainerAnamnesisRouteWithChildren
  '/trainer/anamnesis/_anamnesisLayout': typeof TrainerAnamnesisAnamnesisLayoutRouteWithChildren
  '/trainer/routines/$routineId': typeof TrainerRoutinesRoutineIdRoute
  '/trainer/routines': typeof TrainerRoutinesRouteWithChildren
  '/trainer/routines/_routinesLayout': typeof TrainerRoutinesRoutinesLayoutRouteWithChildren
  '/trainer/workouts/$workoutId': typeof TrainerWorkoutsWorkoutIdRoute
  '/client/anamneses/': typeof ClientAnamnesesIndexRoute
  '/trainer/clients/': typeof TrainerClientsIndexRoute
  '/client/anamneses/$clientAnamnesisId/respond': typeof ClientAnamnesesClientAnamnesisIdRespondRoute
  '/client/sessions/active/save': typeof ClientSessionsActiveSaveRoute
  '/trainer/account/(sections)/conta': typeof TrainerAccountsectionsContaRoute
  '/trainer/account/(sections)/plano': typeof TrainerAccountsectionsPlanoRoute
  '/trainer/account/(sections)/preference': typeof TrainerAccountsectionsPreferenceRoute
  '/trainer/account/(sections)/tema': typeof TrainerAccountsectionsTemaRoute
  '/trainer/clients/$clientId/anamnesis': typeof TrainerClientsClientIdAnamnesisRoute
  '/trainer/clients/$clientId/measurements': typeof TrainerClientsClientIdMeasurementsRoute
  '/trainer/clients/$clientId/overview': typeof TrainerClientsClientIdOverviewRoute
  '/trainer/clients/$clientId/program-history': typeof TrainerClientsClientIdProgramHistoryRoute
  '/trainer/clients/$clientId/weight-evolution': typeof TrainerClientsClientIdWeightEvolutionRoute
  '/trainer/clients/$clientId/workout-session': typeof TrainerClientsClientIdWorkoutSessionRoute
  '/trainer/routines/_routinesLayout/homug-programs': typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  '/client/anamneses/$clientAnamnesisId/': typeof ClientAnamnesesClientAnamnesisIdIndexRoute
  '/trainer/account/(sections)/': typeof TrainerAccountsectionsIndexRoute
  '/trainer/anamnesis/_anamnesisLayout/': typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
  '/trainer/routines/_routinesLayout/': typeof TrainerRoutinesRoutinesLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/trainer'
    | '/email-verified'
    | '/reset-password'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/client/activities'
    | '/client/set-password'
    | '/trainer/analytics'
    | '/trainer/exercises'
    | '/trainer/home'
    | '/trainer/'
    | '/trainer/account'
    | '/trainer/clients/$clientId'
    | '/client/history'
    | '/client/home'
    | '/client/profile'
    | '/client/workouts'
    | '/client/exercises/$exerciseId'
    | '/client/profile/edit'
    | '/client/sessions/active'
    | '/client/sessions/select-exercise'
    | '/trainer/anamnesis/$anamnesisId'
    | '/trainer/anamnesis'
    | '/trainer/routines/$routineId'
    | '/trainer/routines'
    | '/trainer/workouts/$workoutId'
    | '/client/anamneses'
    | '/trainer/clients'
    | '/client/anamneses/$clientAnamnesisId/respond'
    | '/client/sessions/active/save'
    | '/trainer/account/conta'
    | '/trainer/account/plano'
    | '/trainer/account/preference'
    | '/trainer/account/tema'
    | '/trainer/clients/$clientId/anamnesis'
    | '/trainer/clients/$clientId/measurements'
    | '/trainer/clients/$clientId/overview'
    | '/trainer/clients/$clientId/program-history'
    | '/trainer/clients/$clientId/weight-evolution'
    | '/trainer/clients/$clientId/workout-session'
    | '/trainer/routines/homug-programs'
    | '/client/anamneses/$clientAnamnesisId'
    | '/trainer/account/'
    | '/trainer/anamnesis/'
    | '/trainer/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/email-verified'
    | '/reset-password'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/client/activities'
    | '/client/set-password'
    | '/trainer/analytics'
    | '/trainer/exercises'
    | '/trainer/home'
    | '/trainer'
    | '/trainer/clients/$clientId'
    | '/client/history'
    | '/client/home'
    | '/client/profile'
    | '/client/workouts'
    | '/client/exercises/$exerciseId'
    | '/client/profile/edit'
    | '/client/sessions/active'
    | '/client/sessions/select-exercise'
    | '/trainer/anamnesis/$anamnesisId'
    | '/trainer/anamnesis'
    | '/trainer/routines/$routineId'
    | '/trainer/routines'
    | '/trainer/workouts/$workoutId'
    | '/client/anamneses'
    | '/trainer/clients'
    | '/client/anamneses/$clientAnamnesisId/respond'
    | '/client/sessions/active/save'
    | '/trainer/account/conta'
    | '/trainer/account/plano'
    | '/trainer/account/preference'
    | '/trainer/account/tema'
    | '/trainer/clients/$clientId/anamnesis'
    | '/trainer/clients/$clientId/measurements'
    | '/trainer/clients/$clientId/overview'
    | '/trainer/clients/$clientId/program-history'
    | '/trainer/clients/$clientId/weight-evolution'
    | '/trainer/clients/$clientId/workout-session'
    | '/trainer/routines/homug-programs'
    | '/client/anamneses/$clientAnamnesisId'
    | '/trainer/account'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/client'
    | '/trainer'
    | '/email-verified'
    | '/reset-password'
    | '/client/(tabs)'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/client/activities'
    | '/client/set-password'
    | '/trainer/analytics'
    | '/trainer/exercises'
    | '/trainer/home'
    | '/trainer/'
    | '/trainer/account/(sections)'
    | '/trainer/clients/$clientId'
    | '/client/(tabs)/history'
    | '/client/(tabs)/home'
    | '/client/(tabs)/profile'
    | '/client/(tabs)/workouts'
    | '/client/exercises/$exerciseId'
    | '/client/profile/edit'
    | '/client/sessions/active'
    | '/client/sessions/select-exercise'
    | '/trainer/anamnesis/$anamnesisId'
    | '/trainer/anamnesis'
    | '/trainer/anamnesis/_anamnesisLayout'
    | '/trainer/routines/$routineId'
    | '/trainer/routines'
    | '/trainer/routines/_routinesLayout'
    | '/trainer/workouts/$workoutId'
    | '/client/anamneses/'
    | '/trainer/clients/'
    | '/client/anamneses/$clientAnamnesisId/respond'
    | '/client/sessions/active/save'
    | '/trainer/account/(sections)/conta'
    | '/trainer/account/(sections)/plano'
    | '/trainer/account/(sections)/preference'
    | '/trainer/account/(sections)/tema'
    | '/trainer/clients/$clientId/anamnesis'
    | '/trainer/clients/$clientId/measurements'
    | '/trainer/clients/$clientId/overview'
    | '/trainer/clients/$clientId/program-history'
    | '/trainer/clients/$clientId/weight-evolution'
    | '/trainer/clients/$clientId/workout-session'
    | '/trainer/routines/_routinesLayout/homug-programs'
    | '/client/anamneses/$clientAnamnesisId/'
    | '/trainer/account/(sections)/'
    | '/trainer/anamnesis/_anamnesisLayout/'
    | '/trainer/routines/_routinesLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  TrainerRouteRoute: typeof TrainerRouteRouteWithChildren
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/routines': {
      id: '/trainer/routines'
      path: '/routines'
      fullPath: '/trainer/routines'
      preLoaderRoute: typeof TrainerRoutinesRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/anamnesis': {
      id: '/trainer/anamnesis'
      path: '/anamnesis'
      fullPath: '/trainer/anamnesis'
      preLoaderRoute: typeof TrainerAnamnesisRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/home': {
      id: '/trainer/home'
      path: '/home'
      fullPath: '/trainer/home'
      preLoaderRoute: typeof TrainerHomeRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/exercises': {
      id: '/trainer/exercises'
      path: '/exercises'
      fullPath: '/trainer/exercises'
      preLoaderRoute: typeof TrainerExercisesRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/analytics': {
      id: '/trainer/analytics'
      path: '/analytics'
      fullPath: '/trainer/analytics'
      preLoaderRoute: typeof TrainerAnalyticsRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/client/set-password': {
      id: '/client/set-password'
      path: '/set-password'
      fullPath: '/client/set-password'
      preLoaderRoute: typeof ClientSetPasswordRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/activities': {
      id: '/client/activities'
      path: '/activities'
      fullPath: '/client/activities'
      preLoaderRoute: typeof ClientActivitiesRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/client/(tabs)': {
      id: '/client/(tabs)'
      path: ''
      fullPath: '/client'
      preLoaderRoute: typeof ClienttabsRouteRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/trainer/clients/': {
      id: '/trainer/clients/'
      path: '/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsIndexRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/client/anamneses/': {
      id: '/client/anamneses/'
      path: '/anamneses'
      fullPath: '/client/anamneses'
      preLoaderRoute: typeof ClientAnamnesesIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/trainer/workouts/$workoutId': {
      id: '/trainer/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/trainer/workouts/$workoutId'
      preLoaderRoute: typeof TrainerWorkoutsWorkoutIdRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/routines/_routinesLayout': {
      id: '/trainer/routines/_routinesLayout'
      path: '/routines'
      fullPath: '/trainer/routines'
      preLoaderRoute: typeof TrainerRoutinesRoutinesLayoutRouteImport
      parentRoute: typeof TrainerRoutinesRoute
    }
    '/trainer/routines/$routineId': {
      id: '/trainer/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/trainer/routines/$routineId'
      preLoaderRoute: typeof TrainerRoutinesRoutineIdRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/anamnesis/_anamnesisLayout': {
      id: '/trainer/anamnesis/_anamnesisLayout'
      path: '/anamnesis'
      fullPath: '/trainer/anamnesis'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisLayoutRouteImport
      parentRoute: typeof TrainerAnamnesisRoute
    }
    '/trainer/anamnesis/$anamnesisId': {
      id: '/trainer/anamnesis/$anamnesisId'
      path: '/anamnesis/$anamnesisId'
      fullPath: '/trainer/anamnesis/$anamnesisId'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisIdRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/client/sessions/select-exercise': {
      id: '/client/sessions/select-exercise'
      path: '/sessions/select-exercise'
      fullPath: '/client/sessions/select-exercise'
      preLoaderRoute: typeof ClientSessionsSelectExerciseRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/sessions/active': {
      id: '/client/sessions/active'
      path: '/sessions/active'
      fullPath: '/client/sessions/active'
      preLoaderRoute: typeof ClientSessionsActiveRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/profile/edit': {
      id: '/client/profile/edit'
      path: '/profile/edit'
      fullPath: '/client/profile/edit'
      preLoaderRoute: typeof ClientProfileEditRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/exercises/$exerciseId': {
      id: '/client/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/client/exercises/$exerciseId'
      preLoaderRoute: typeof ClientExercisesExerciseIdRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/client/(tabs)/workouts': {
      id: '/client/(tabs)/workouts'
      path: '/workouts'
      fullPath: '/client/workouts'
      preLoaderRoute: typeof ClienttabsWorkoutsRouteImport
      parentRoute: typeof ClienttabsRouteRoute
    }
    '/client/(tabs)/profile': {
      id: '/client/(tabs)/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClienttabsProfileRouteImport
      parentRoute: typeof ClienttabsRouteRoute
    }
    '/client/(tabs)/home': {
      id: '/client/(tabs)/home'
      path: '/home'
      fullPath: '/client/home'
      preLoaderRoute: typeof ClienttabsHomeRouteImport
      parentRoute: typeof ClienttabsRouteRoute
    }
    '/client/(tabs)/history': {
      id: '/client/(tabs)/history'
      path: '/history'
      fullPath: '/client/history'
      preLoaderRoute: typeof ClienttabsHistoryRouteImport
      parentRoute: typeof ClienttabsRouteRoute
    }
    '/trainer/clients/$clientId': {
      id: '/trainer/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/trainer/clients/$clientId'
      preLoaderRoute: typeof TrainerClientsClientIdRouteRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/account/(sections)': {
      id: '/trainer/account/(sections)'
      path: '/account'
      fullPath: '/trainer/account'
      preLoaderRoute: typeof TrainerAccountsectionsRouteRouteImport
      parentRoute: typeof TrainerRouteRoute
    }
    '/trainer/routines/_routinesLayout/': {
      id: '/trainer/routines/_routinesLayout/'
      path: '/'
      fullPath: '/trainer/routines/'
      preLoaderRoute: typeof TrainerRoutinesRoutinesLayoutIndexRouteImport
      parentRoute: typeof TrainerRoutinesRoutinesLayoutRoute
    }
    '/trainer/anamnesis/_anamnesisLayout/': {
      id: '/trainer/anamnesis/_anamnesisLayout/'
      path: '/'
      fullPath: '/trainer/anamnesis/'
      preLoaderRoute: typeof TrainerAnamnesisAnamnesisLayoutIndexRouteImport
      parentRoute: typeof TrainerAnamnesisAnamnesisLayoutRoute
    }
    '/trainer/account/(sections)/': {
      id: '/trainer/account/(sections)/'
      path: '/'
      fullPath: '/trainer/account/'
      preLoaderRoute: typeof TrainerAccountsectionsIndexRouteImport
      parentRoute: typeof TrainerAccountsectionsRouteRoute
    }
    '/client/anamneses/$clientAnamnesisId/': {
      id: '/client/anamneses/$clientAnamnesisId/'
      path: '/anamneses/$clientAnamnesisId'
      fullPath: '/client/anamneses/$clientAnamnesisId'
      preLoaderRoute: typeof ClientAnamnesesClientAnamnesisIdIndexRouteImport
      parentRoute: typeof ClientRouteRoute
    }
    '/trainer/routines/_routinesLayout/homug-programs': {
      id: '/trainer/routines/_routinesLayout/homug-programs'
      path: '/homug-programs'
      fullPath: '/trainer/routines/homug-programs'
      preLoaderRoute: typeof TrainerRoutinesRoutinesLayoutHomugProgramsRouteImport
      parentRoute: typeof TrainerRoutinesRoutinesLayoutRoute
    }
    '/trainer/clients/$clientId/workout-session': {
      id: '/trainer/clients/$clientId/workout-session'
      path: '/workout-session'
      fullPath: '/trainer/clients/$clientId/workout-session'
      preLoaderRoute: typeof TrainerClientsClientIdWorkoutSessionRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/weight-evolution': {
      id: '/trainer/clients/$clientId/weight-evolution'
      path: '/weight-evolution'
      fullPath: '/trainer/clients/$clientId/weight-evolution'
      preLoaderRoute: typeof TrainerClientsClientIdWeightEvolutionRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/program-history': {
      id: '/trainer/clients/$clientId/program-history'
      path: '/program-history'
      fullPath: '/trainer/clients/$clientId/program-history'
      preLoaderRoute: typeof TrainerClientsClientIdProgramHistoryRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/overview': {
      id: '/trainer/clients/$clientId/overview'
      path: '/overview'
      fullPath: '/trainer/clients/$clientId/overview'
      preLoaderRoute: typeof TrainerClientsClientIdOverviewRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/measurements': {
      id: '/trainer/clients/$clientId/measurements'
      path: '/measurements'
      fullPath: '/trainer/clients/$clientId/measurements'
      preLoaderRoute: typeof TrainerClientsClientIdMeasurementsRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/clients/$clientId/anamnesis': {
      id: '/trainer/clients/$clientId/anamnesis'
      path: '/anamnesis'
      fullPath: '/trainer/clients/$clientId/anamnesis'
      preLoaderRoute: typeof TrainerClientsClientIdAnamnesisRouteImport
      parentRoute: typeof TrainerClientsClientIdRouteRoute
    }
    '/trainer/account/(sections)/tema': {
      id: '/trainer/account/(sections)/tema'
      path: '/tema'
      fullPath: '/trainer/account/tema'
      preLoaderRoute: typeof TrainerAccountsectionsTemaRouteImport
      parentRoute: typeof TrainerAccountsectionsRouteRoute
    }
    '/trainer/account/(sections)/preference': {
      id: '/trainer/account/(sections)/preference'
      path: '/preference'
      fullPath: '/trainer/account/preference'
      preLoaderRoute: typeof TrainerAccountsectionsPreferenceRouteImport
      parentRoute: typeof TrainerAccountsectionsRouteRoute
    }
    '/trainer/account/(sections)/plano': {
      id: '/trainer/account/(sections)/plano'
      path: '/plano'
      fullPath: '/trainer/account/plano'
      preLoaderRoute: typeof TrainerAccountsectionsPlanoRouteImport
      parentRoute: typeof TrainerAccountsectionsRouteRoute
    }
    '/trainer/account/(sections)/conta': {
      id: '/trainer/account/(sections)/conta'
      path: '/conta'
      fullPath: '/trainer/account/conta'
      preLoaderRoute: typeof TrainerAccountsectionsContaRouteImport
      parentRoute: typeof TrainerAccountsectionsRouteRoute
    }
    '/client/sessions/active/save': {
      id: '/client/sessions/active/save'
      path: '/save'
      fullPath: '/client/sessions/active/save'
      preLoaderRoute: typeof ClientSessionsActiveSaveRouteImport
      parentRoute: typeof ClientSessionsActiveRoute
    }
    '/client/anamneses/$clientAnamnesisId/respond': {
      id: '/client/anamneses/$clientAnamnesisId/respond'
      path: '/anamneses/$clientAnamnesisId/respond'
      fullPath: '/client/anamneses/$clientAnamnesisId/respond'
      preLoaderRoute: typeof ClientAnamnesesClientAnamnesisIdRespondRouteImport
      parentRoute: typeof ClientRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ClienttabsRouteRouteChildren {
  ClienttabsHistoryRoute: typeof ClienttabsHistoryRoute
  ClienttabsHomeRoute: typeof ClienttabsHomeRoute
  ClienttabsProfileRoute: typeof ClienttabsProfileRoute
  ClienttabsWorkoutsRoute: typeof ClienttabsWorkoutsRoute
}

const ClienttabsRouteRouteChildren: ClienttabsRouteRouteChildren = {
  ClienttabsHistoryRoute: ClienttabsHistoryRoute,
  ClienttabsHomeRoute: ClienttabsHomeRoute,
  ClienttabsProfileRoute: ClienttabsProfileRoute,
  ClienttabsWorkoutsRoute: ClienttabsWorkoutsRoute,
}

const ClienttabsRouteRouteWithChildren = ClienttabsRouteRoute._addFileChildren(
  ClienttabsRouteRouteChildren,
)

interface ClientSessionsActiveRouteChildren {
  ClientSessionsActiveSaveRoute: typeof ClientSessionsActiveSaveRoute
}

const ClientSessionsActiveRouteChildren: ClientSessionsActiveRouteChildren = {
  ClientSessionsActiveSaveRoute: ClientSessionsActiveSaveRoute,
}

const ClientSessionsActiveRouteWithChildren =
  ClientSessionsActiveRoute._addFileChildren(ClientSessionsActiveRouteChildren)

interface ClientRouteRouteChildren {
  ClienttabsRouteRoute: typeof ClienttabsRouteRouteWithChildren
  ClientActivitiesRoute: typeof ClientActivitiesRoute
  ClientSetPasswordRoute: typeof ClientSetPasswordRoute
  ClientExercisesExerciseIdRoute: typeof ClientExercisesExerciseIdRoute
  ClientProfileEditRoute: typeof ClientProfileEditRoute
  ClientSessionsActiveRoute: typeof ClientSessionsActiveRouteWithChildren
  ClientSessionsSelectExerciseRoute: typeof ClientSessionsSelectExerciseRoute
  ClientAnamnesesIndexRoute: typeof ClientAnamnesesIndexRoute
  ClientAnamnesesClientAnamnesisIdRespondRoute: typeof ClientAnamnesesClientAnamnesisIdRespondRoute
  ClientAnamnesesClientAnamnesisIdIndexRoute: typeof ClientAnamnesesClientAnamnesisIdIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClienttabsRouteRoute: ClienttabsRouteRouteWithChildren,
  ClientActivitiesRoute: ClientActivitiesRoute,
  ClientSetPasswordRoute: ClientSetPasswordRoute,
  ClientExercisesExerciseIdRoute: ClientExercisesExerciseIdRoute,
  ClientProfileEditRoute: ClientProfileEditRoute,
  ClientSessionsActiveRoute: ClientSessionsActiveRouteWithChildren,
  ClientSessionsSelectExerciseRoute: ClientSessionsSelectExerciseRoute,
  ClientAnamnesesIndexRoute: ClientAnamnesesIndexRoute,
  ClientAnamnesesClientAnamnesisIdRespondRoute:
    ClientAnamnesesClientAnamnesisIdRespondRoute,
  ClientAnamnesesClientAnamnesisIdIndexRoute:
    ClientAnamnesesClientAnamnesisIdIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

interface TrainerAccountsectionsRouteRouteChildren {
  TrainerAccountsectionsContaRoute: typeof TrainerAccountsectionsContaRoute
  TrainerAccountsectionsPlanoRoute: typeof TrainerAccountsectionsPlanoRoute
  TrainerAccountsectionsPreferenceRoute: typeof TrainerAccountsectionsPreferenceRoute
  TrainerAccountsectionsTemaRoute: typeof TrainerAccountsectionsTemaRoute
  TrainerAccountsectionsIndexRoute: typeof TrainerAccountsectionsIndexRoute
}

const TrainerAccountsectionsRouteRouteChildren: TrainerAccountsectionsRouteRouteChildren =
  {
    TrainerAccountsectionsContaRoute: TrainerAccountsectionsContaRoute,
    TrainerAccountsectionsPlanoRoute: TrainerAccountsectionsPlanoRoute,
    TrainerAccountsectionsPreferenceRoute:
      TrainerAccountsectionsPreferenceRoute,
    TrainerAccountsectionsTemaRoute: TrainerAccountsectionsTemaRoute,
    TrainerAccountsectionsIndexRoute: TrainerAccountsectionsIndexRoute,
  }

const TrainerAccountsectionsRouteRouteWithChildren =
  TrainerAccountsectionsRouteRoute._addFileChildren(
    TrainerAccountsectionsRouteRouteChildren,
  )

interface TrainerClientsClientIdRouteRouteChildren {
  TrainerClientsClientIdAnamnesisRoute: typeof TrainerClientsClientIdAnamnesisRoute
  TrainerClientsClientIdMeasurementsRoute: typeof TrainerClientsClientIdMeasurementsRoute
  TrainerClientsClientIdOverviewRoute: typeof TrainerClientsClientIdOverviewRoute
  TrainerClientsClientIdProgramHistoryRoute: typeof TrainerClientsClientIdProgramHistoryRoute
  TrainerClientsClientIdWeightEvolutionRoute: typeof TrainerClientsClientIdWeightEvolutionRoute
  TrainerClientsClientIdWorkoutSessionRoute: typeof TrainerClientsClientIdWorkoutSessionRoute
}

const TrainerClientsClientIdRouteRouteChildren: TrainerClientsClientIdRouteRouteChildren =
  {
    TrainerClientsClientIdAnamnesisRoute: TrainerClientsClientIdAnamnesisRoute,
    TrainerClientsClientIdMeasurementsRoute:
      TrainerClientsClientIdMeasurementsRoute,
    TrainerClientsClientIdOverviewRoute: TrainerClientsClientIdOverviewRoute,
    TrainerClientsClientIdProgramHistoryRoute:
      TrainerClientsClientIdProgramHistoryRoute,
    TrainerClientsClientIdWeightEvolutionRoute:
      TrainerClientsClientIdWeightEvolutionRoute,
    TrainerClientsClientIdWorkoutSessionRoute:
      TrainerClientsClientIdWorkoutSessionRoute,
  }

const TrainerClientsClientIdRouteRouteWithChildren =
  TrainerClientsClientIdRouteRoute._addFileChildren(
    TrainerClientsClientIdRouteRouteChildren,
  )

interface TrainerAnamnesisAnamnesisLayoutRouteChildren {
  TrainerAnamnesisAnamnesisLayoutIndexRoute: typeof TrainerAnamnesisAnamnesisLayoutIndexRoute
}

const TrainerAnamnesisAnamnesisLayoutRouteChildren: TrainerAnamnesisAnamnesisLayoutRouteChildren =
  {
    TrainerAnamnesisAnamnesisLayoutIndexRoute:
      TrainerAnamnesisAnamnesisLayoutIndexRoute,
  }

const TrainerAnamnesisAnamnesisLayoutRouteWithChildren =
  TrainerAnamnesisAnamnesisLayoutRoute._addFileChildren(
    TrainerAnamnesisAnamnesisLayoutRouteChildren,
  )

interface TrainerAnamnesisRouteChildren {
  TrainerAnamnesisAnamnesisLayoutRoute: typeof TrainerAnamnesisAnamnesisLayoutRouteWithChildren
}

const TrainerAnamnesisRouteChildren: TrainerAnamnesisRouteChildren = {
  TrainerAnamnesisAnamnesisLayoutRoute:
    TrainerAnamnesisAnamnesisLayoutRouteWithChildren,
}

const TrainerAnamnesisRouteWithChildren =
  TrainerAnamnesisRoute._addFileChildren(TrainerAnamnesisRouteChildren)

interface TrainerRoutinesRoutinesLayoutRouteChildren {
  TrainerRoutinesRoutinesLayoutHomugProgramsRoute: typeof TrainerRoutinesRoutinesLayoutHomugProgramsRoute
  TrainerRoutinesRoutinesLayoutIndexRoute: typeof TrainerRoutinesRoutinesLayoutIndexRoute
}

const TrainerRoutinesRoutinesLayoutRouteChildren: TrainerRoutinesRoutinesLayoutRouteChildren =
  {
    TrainerRoutinesRoutinesLayoutHomugProgramsRoute:
      TrainerRoutinesRoutinesLayoutHomugProgramsRoute,
    TrainerRoutinesRoutinesLayoutIndexRoute:
      TrainerRoutinesRoutinesLayoutIndexRoute,
  }

const TrainerRoutinesRoutinesLayoutRouteWithChildren =
  TrainerRoutinesRoutinesLayoutRoute._addFileChildren(
    TrainerRoutinesRoutinesLayoutRouteChildren,
  )

interface TrainerRoutinesRouteChildren {
  TrainerRoutinesRoutinesLayoutRoute: typeof TrainerRoutinesRoutinesLayoutRouteWithChildren
}

const TrainerRoutinesRouteChildren: TrainerRoutinesRouteChildren = {
  TrainerRoutinesRoutinesLayoutRoute:
    TrainerRoutinesRoutinesLayoutRouteWithChildren,
}

const TrainerRoutinesRouteWithChildren = TrainerRoutinesRoute._addFileChildren(
  TrainerRoutinesRouteChildren,
)

interface TrainerRouteRouteChildren {
  TrainerAnalyticsRoute: typeof TrainerAnalyticsRoute
  TrainerExercisesRoute: typeof TrainerExercisesRoute
  TrainerHomeRoute: typeof TrainerHomeRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
  TrainerAccountsectionsRouteRoute: typeof TrainerAccountsectionsRouteRouteWithChildren
  TrainerClientsClientIdRouteRoute: typeof TrainerClientsClientIdRouteRouteWithChildren
  TrainerAnamnesisAnamnesisIdRoute: typeof TrainerAnamnesisAnamnesisIdRoute
  TrainerAnamnesisRoute: typeof TrainerAnamnesisRouteWithChildren
  TrainerRoutinesRoutineIdRoute: typeof TrainerRoutinesRoutineIdRoute
  TrainerRoutinesRoute: typeof TrainerRoutinesRouteWithChildren
  TrainerWorkoutsWorkoutIdRoute: typeof TrainerWorkoutsWorkoutIdRoute
  TrainerClientsIndexRoute: typeof TrainerClientsIndexRoute
}

const TrainerRouteRouteChildren: TrainerRouteRouteChildren = {
  TrainerAnalyticsRoute: TrainerAnalyticsRoute,
  TrainerExercisesRoute: TrainerExercisesRoute,
  TrainerHomeRoute: TrainerHomeRoute,
  TrainerIndexRoute: TrainerIndexRoute,
  TrainerAccountsectionsRouteRoute:
    TrainerAccountsectionsRouteRouteWithChildren,
  TrainerClientsClientIdRouteRoute:
    TrainerClientsClientIdRouteRouteWithChildren,
  TrainerAnamnesisAnamnesisIdRoute: TrainerAnamnesisAnamnesisIdRoute,
  TrainerAnamnesisRoute: TrainerAnamnesisRouteWithChildren,
  TrainerRoutinesRoutineIdRoute: TrainerRoutinesRoutineIdRoute,
  TrainerRoutinesRoute: TrainerRoutinesRouteWithChildren,
  TrainerWorkoutsWorkoutIdRoute: TrainerWorkoutsWorkoutIdRoute,
  TrainerClientsIndexRoute: TrainerClientsIndexRoute,
}

const TrainerRouteRouteWithChildren = TrainerRouteRoute._addFileChildren(
  TrainerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ClientRouteRoute: ClientRouteRouteWithChildren,
  TrainerRouteRoute: TrainerRouteRouteWithChildren,
  EmailVerifiedRoute: EmailVerifiedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
